#ifndef GEOMETRY_H
#define GEOMETRY_H

enum GEOMETRY_TYPE {

	GEO_LIGHTBALL = 0,
	GEO_SPHERE,
	GEO_AXES,
	GEO_QUAD,
	GEO_CUBE,
	GEO_CIRCLE,
	GEO_CYLINDER,
	GEO_CONE,
	GEO_RING,
	GEO_HEMISPHERE,
	GEO_SQUARE_PYRAMID,
	GEO_TRIANGLE_PYRAMID,
	GEO_DIAMOND_QUAD,
	GEO_TRIANGLE_CUBOID,
	GEO_HOLLOW_CYLINDER,

	// Misc
	GEO_FLOOR,
	GEO_SIGNBOARD_TOP,
	GEO_SIGNBOARD_POLE,

	// Weapon
	GEO_SWORD_BLADE,

	// Head
	GEO_HEAD_CANNON,
	GEO_HEAD_CONNECTOR_BRANCH,
	GEO_HEAD_CONNECTOR_BASE,
	GEO_HEAD_SKULL_FRONT,
	GEO_HEAD_SKULL_BACK,
	GEO_HEAD_FACE_EYE,
	GEO_HEAD_FACE_EYE_SHADOW,
	GEO_HEAD_FACE_MOUTH,


	// Shoulder
	GEO_SHOULDER_CANNON_BARREL,
	GEO_SHOULDER_CANNON_BUTT,
	GEO_SHOULDER_SHOULDER,
	GEO_SHOULDER_ARMJOINT,
	GEO_SHOULDER_CHARGED_PARTICLE,

	// Arm
	GEO_ARM_AMMO_TOP,
	GEO_ARM_AMMO_BOTTOM,
	GEO_ARM_JOINT,
	GEO_ARM_MUZZLE,
	GEO_ARM_HAND,

	// Chest
	GEO_CHEST_NECK_JOINT,
	GEO_CHEST_LEFT_JOINT,
	GEO_CHEST_RIGHT_JOINT,
	GEO_CHEST_ABDOMEN_JOINT,
	GEO_CHEST_INNER_ARMOR_FRONT,
	GEO_CHEST_INNER_ARMOR_BACK,
	GEO_CHEST_OUTER_ARMOR_FRONT,
	GEO_CHEST_CHARGED_BALL,

	// Abdomen
	GEO_ABDOMEN_INNER_ARMOR_TOP,
	GEO_ABDOMEN_INNER_ARMOR_BOTTOM,
	GEO_ABDOMEN_OUTER_ARMOR_TOP,
	GEO_ABDOMEN_OUTER_ARMOR_BOTTOM,

	// Thigh
	GEO_THIGH_THIGH,

	// Foot
	GEO_FOOT_JOINT,
	GEO_FOOT_SHIN,
	GEO_FOOT_FOOT,


	NUM_GEOMETRY
};

enum UNIFORM_TYPE {

	U_MVP = 0,
	U_MODELVIEW,
	U_MODELVIEW_INVERSE_TRANSPOSE,
	U_MATERIAL_AMBIENT,
	U_MATERIAL_DIFFUSE,
	U_MATERIAL_SPECULAR,
	U_MATERIAL_SHININESS,

	U_LIGHT0_POSITION,
	U_LIGHT0_COLOR,
	U_LIGHT0_POWER,
	U_LIGHT0_KC,
	U_LIGHT0_KL,
	U_LIGHT0_KQ,
	U_LIGHT0_TYPE,
	U_LIGHT0_SPOTDIRECTION,
	U_LIGHT0_COSCUTOFF,
	U_LIGHT0_COSINNER,
	U_LIGHT0_EXPONENT,

	U_LIGHT1_POSITION,
	U_LIGHT1_COLOR,
	U_LIGHT1_POWER,
	U_LIGHT1_KC,
	U_LIGHT1_KL,
	U_LIGHT1_KQ,
	U_LIGHT1_TYPE,
	U_LIGHT1_SPOTDIRECTION,
	U_LIGHT1_COSCUTOFF,
	U_LIGHT1_COSINNER,
	U_LIGHT1_EXPONENT,

	U_LIGHTENABLED,
	U_NUMLIGHTS,

	U_COLOR_TEXTURE_ENABLED,
	U_COLOR_TEXTURE,

	U_TEXT_ENABLED,
	U_TEXT_COLOR,

	U_TOTAL,

};

#endif